### PR TITLE
[Wisp] Fix intermittent wisp test failure

### PR DESCRIPTION
**Pull request by joeyleeeeeee97**
Summary: fix unstable wisp tests

Test Plan: jtreg test/com/alibaba/

Reviewed-by: yuleil, sanhong.lsh

Issue: https://github.com/alibaba/dragonwell8/issues/163

### CODE REVIEW

**Comment by joeyleeeeeee97** [comment]
test

**Comment by joeyleeeeeee97** [comment]
run tests.

**Comment by joeyleeeeeee97** [comment]
run tests.

**Review by yuleil — APPROVED** [review]

**Review by zhengxiaolinX — APPROVED** [review]
LGTM.

**Pull request merged**
